### ISSUE TITLE
SIG Core Chair & Co-Chair Election 2024 - 2025

### ISSUE THREAD

**Issue by Naomi-Wash** [o3de/sig-core#62]
SIG Core has been inactive due to lack of a chair and co-chair. Opening an election for both seats that will begin in 2024 and carry to the end of 2025. 

Responsibility of Chair(s) https://github.com/o3de/community/blob/1563c74bd99c4a4d2896e00d1d53400dbb9f436a/sigs/docs/sig-governance.md#responsibility-of-chairs
_Co-chairs are to support the role of the chair_

You can see the election process here:
https://github.com/o3de/community/blob/main/O3DE%20Elections/O3DE%20Elections%20Guide.md

```[tasklist]
### Tasks
- [x] Decides the nomination and election timeline.
- [x] **Nomination Period: October 29 - November 15, 2024** | Submit nominations to this GHI - include Name, Company, brief background and why you are a good fit for chair/co-chair. You can nominate yourself or another person, but if you nominate someone please be sure they are aware of your nomination.
- [x] **Election Period: November 18 - 27, 2024** | 2 or more submissions for each position will result in a election poll/voting survey.
- [x] On Discord, create an event that links to the GitHub Issue and uses the same issue title, mentioning the nomination and voting dates, and the SIG name.
- [x] Share the event in the SIG Channel, along with the mailing list.
- [x] Monitor the channel during the nomination process, responding to questions, and checking for nominations, acceptances, or declines. Send out reminders as necessary. If there is only one nominee, extend the nomination period by 1-2 weeks. If no one is nominated, the suggested candidate will become the Chair/Co-Chair.
- [x] Prepare & send the election poll/voting survey
- [x] Announce the results of the Issue and the SIG Channel
```

### New members seated: 1 December 2024

**Comment by byrcolin** [comment]
I nominate @spham-amzn for Sig/Core Chair

**Comment by spham-amzn** [comment]
### SIG-Core Chair Nomination

I would like to nominate myself: ***spham-amzn***, to become a ***Chair*** on behalf of ***sig-core***. 

* Nominee's GitHub Profile ***< https://github.com/spham-amzn >***

### About myself
I currently work for Amazon Web Services. I've been with Amazon for 13 years. I have about 28 years of professional software development experience (https://www.linkedin.com/in/steve-pham-69a7142/)

### Why am I a good fit
I've been involved with O3DE since its release, including its life as the Lumberyard Engine by Amazon, and heavily participated in the effort to open source it to O3DE (Totaling almost 10 years). Most the contributions I make to O3DE are system related and I have a solid understanding of the core system. Some of my larger contributions to O3DE are:

* Bringing up the code to have Linux support on Parity with Windows
* Enabling Python virtual environments
* Linux ARM64 Support
* Android Platform Support
* GCC build support
* Lumberyard WAF -> CMake migration
* Dockerization Support


*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by Ulrick28** [comment]
I nominate Nick Lawson for co-chair. Nick currently leads the TSC and knows the core of O3DE well. He will be a good partner for whoever eventually becomes the chair.

Nominee's GitHub Profile < https://github.com/nick-l-o3de> 

Why a good fit: Nick has authored or resolved issues in several core systems of O3DE. These include the build system, no code project, resolving threading issues, resolving Asset Processing issues, and many more. Nick has been a part of O3DE since it's inception and is currently the TSC chair.

**Comment by Naomi-Wash** [comment]
Since there was one submission for the chair position, the nominee is automatically elected.

@spham-amzn is the Chair.

**Comment by nick-l-o3de** [comment]
I can handle co-chair, but I might not be able to make every meeting.

**Comment by Naomi-Wash** [comment]
Thank you, @nick-l-o3de . Closing this issue as now the only co-chair nominee has accepted the position.
